require('dotenv').config();
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const contentData = [
  // AI category
  { title: 'Introduction to Machine Learning', description: 'Learn the fundamental concepts of ML: supervised, unsupervised, and reinforcement learning. Perfect starting point for anyone curious about AI.', category: 'ai', type: 'tutorial', difficulty: 'beginner', duration: '30min', tags: JSON.stringify(['ml', 'ai', 'python', 'basics']), goalTags: JSON.stringify(['learn-ai', 'learn-programming']), imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Build Your First Neural Network', description: 'Hands-on project: implement a neural network from scratch using Python and NumPy. Understand backpropagation intuitively.', category: 'ai', type: 'project', difficulty: 'intermediate', duration: '2hr+', tags: JSON.stringify(['neural-networks', 'python', 'deep-learning']), goalTags: JSON.stringify(['learn-ai', 'learn-programming']), imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Prompt Engineering Masterclass', description: 'Learn advanced techniques to craft effective prompts for LLMs. Includes chain-of-thought, few-shot, and structured output patterns.', category: 'ai', type: 'tutorial', difficulty: 'intermediate', duration: '1hr', tags: JSON.stringify(['llm', 'prompting', 'gpt', 'gemini']), goalTags: JSON.stringify(['learn-ai', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'AI Ethics and Responsible Development', description: 'Understand bias, fairness, transparency, and accountability in AI systems. A must-read for every AI practitioner.', category: 'ai', type: 'article', difficulty: 'beginner', duration: '15min', tags: JSON.stringify(['ethics', 'ai', 'responsibility']), goalTags: JSON.stringify(['learn-ai', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'RAG Systems: Retrieval Augmented Generation', description: 'Build production-ready RAG pipelines. Learn vector databases, embeddings, and hybrid search for real-world AI applications.', category: 'ai', type: 'project', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['rag', 'llm', 'vector-db', 'langchain']), goalTags: JSON.stringify(['learn-ai', 'build-startup']), imageUrl: 'https://images.unsplash.com/photo-1639322537228-f710d846310a?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Fine-tuning LLMs for Custom Use Cases', description: 'Learn LoRA, QLoRA, and PEFT techniques to fine-tune large language models on your own data. Includes practical examples.', category: 'ai', type: 'tutorial', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['fine-tuning', 'lora', 'llm', 'training']), goalTags: JSON.stringify(['learn-ai', 'build-startup']), imageUrl: 'https://images.unsplash.com/photo-1666875753105-c63a6f3bdc86?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'AI in 5 Minutes: Daily Concepts', description: 'Quick bite-sized AI concepts explained simply. Perfect for beginners who want to learn AI without overwhelming detail.', category: 'ai', type: 'article', difficulty: 'beginner', duration: '15min', tags: JSON.stringify(['ai', 'basics', 'quick-learn']), goalTags: JSON.stringify(['learn-ai']), imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&q=80', author: 'AdaptiveAI' },

  // Web Development
  { title: 'React 18 Fundamentals', description: 'Master the latest React features: Concurrent Mode, Suspense, Server Components, and the new hooks. Build a real app from scratch.', category: 'webdev', type: 'tutorial', difficulty: 'beginner', duration: '2hr+', tags: JSON.stringify(['react', 'javascript', 'frontend']), goalTags: JSON.stringify(['learn-programming', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Full-Stack Next.js App with Auth', description: 'Build a production-ready full-stack app: Next.js 14, Prisma, PostgreSQL, NextAuth. Deploy to Vercel.', category: 'webdev', type: 'project', difficulty: 'intermediate', duration: '2hr+', tags: JSON.stringify(['nextjs', 'fullstack', 'auth', 'prisma']), goalTags: JSON.stringify(['learn-programming', 'build-startup']), imageUrl: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'CSS Grid & Flexbox Mastery', description: 'Stop struggling with CSS layouts. Master Grid and Flexbox with 20 practical exercises and real-world patterns.', category: 'webdev', type: 'challenge', difficulty: 'beginner', duration: '1hr', tags: JSON.stringify(['css', 'grid', 'flexbox', 'design']), goalTags: JSON.stringify(['learn-programming']), imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Advanced TypeScript Patterns', description: 'Generics, conditional types, mapped types, template literals, and declaration merging. For developers who want to write bulletproof code.', category: 'webdev', type: 'tutorial', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['typescript', 'advanced', 'patterns']), goalTags: JSON.stringify(['learn-programming', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1587620962725-abab19836100?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'API Design Best Practices', description: 'RESTful design, versioning, authentication, rate limiting, documentation, and error handling for production APIs.', category: 'webdev', type: 'article', difficulty: 'intermediate', duration: '30min', tags: JSON.stringify(['api', 'rest', 'backend', 'design']), goalTags: JSON.stringify(['learn-programming', 'build-startup']), imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&q=80', author: 'AdaptiveAI' },

  // Business & Startup
  { title: 'From Idea to MVP in 30 Days', description: 'Actionable framework for indie hackers and startup founders. Validate, build, launch, and get first customers.', category: 'business', type: 'tutorial', difficulty: 'beginner', duration: '1hr', tags: JSON.stringify(['startup', 'mvp', 'entrepreneurship', 'validation']), goalTags: JSON.stringify(['build-startup', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'AI Startup Landscape 2024', description: 'Market analysis of AI startups: opportunities, competitive moats, funding trends, and where the next unicorns might emerge.', category: 'business', type: 'article', difficulty: 'intermediate', duration: '30min', tags: JSON.stringify(['ai', 'startup', 'market', 'trends']), goalTags: JSON.stringify(['build-startup', 'learn-ai']), imageUrl: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'SaaS Pricing Strategy Deep Dive', description: 'How to price your SaaS: freemium, usage-based, tiered, enterprise. Includes case studies from successful companies.', category: 'business', type: 'article', difficulty: 'intermediate', duration: '30min', tags: JSON.stringify(['saas', 'pricing', 'business', 'monetization']), goalTags: JSON.stringify(['build-startup']), imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Technical Architecture for Startups', description: 'Choose the right tech stack, avoid premature optimization, design for scale without over-engineering. Real decisions, real trade-offs.', category: 'business', type: 'project', difficulty: 'advanced', duration: '1hr', tags: JSON.stringify(['architecture', 'startup', 'technical', 'scaling']), goalTags: JSON.stringify(['build-startup', 'learn-programming']), imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=80', author: 'AdaptiveAI' },

  // Career & Productivity
  { title: 'Ace Your Technical Interview', description: 'Data structures, algorithms, system design, and behavioral questions. With 50 practice problems and solutions.', category: 'career', type: 'challenge', difficulty: 'intermediate', duration: '2hr+', tags: JSON.stringify(['interview', 'dsa', 'system-design', 'career']), goalTags: JSON.stringify(['prepare-interviews', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Personal Productivity System for Developers', description: 'Time blocking, deep work, the developer flow state, task management, and avoiding burnout. Build a sustainable work system.', category: 'career', type: 'article', difficulty: 'beginner', duration: '15min', tags: JSON.stringify(['productivity', 'developer', 'career', 'habits']), goalTags: JSON.stringify(['improve-productivity', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Building Your Developer Brand', description: 'GitHub profile, technical writing, open source contributions, speaking, and LinkedIn for developers. Stand out in the job market.', category: 'career', type: 'tutorial', difficulty: 'beginner', duration: '30min', tags: JSON.stringify(['personal-brand', 'career', 'github', 'writing']), goalTags: JSON.stringify(['improve-career', 'improve-communication']), imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'System Design: Scale to Millions', description: 'Design Twitter, Netflix, Uber. Learn load balancing, caching, databases, microservices, and distributed systems.', category: 'career', type: 'project', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['system-design', 'distributed', 'scalability', 'architecture']), goalTags: JSON.stringify(['prepare-interviews', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80', author: 'AdaptiveAI' },

  // Data Science
  { title: 'Python for Data Science: Complete Guide', description: 'Pandas, NumPy, Matplotlib, Seaborn, and scikit-learn. From data loading to model deployment.', category: 'data-science', type: 'tutorial', difficulty: 'beginner', duration: '2hr+', tags: JSON.stringify(['python', 'data-science', 'pandas', 'ml']), goalTags: JSON.stringify(['learn-ai', 'learn-programming']), imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Statistical Analysis for Product Decisions', description: 'A/B testing, cohort analysis, funnel analysis, and statistical significance. Make data-driven decisions.', category: 'data-science', type: 'tutorial', difficulty: 'intermediate', duration: '1hr', tags: JSON.stringify(['statistics', 'product', 'analysis', 'ab-testing']), goalTags: JSON.stringify(['improve-productivity', 'build-startup']), imageUrl: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=400&q=80', author: 'AdaptiveAI' },

  // Design
  { title: 'UI/UX Design Principles for Developers', description: 'Typography, color theory, spacing, component design, and accessibility. Make your projects look professional.', category: 'design', type: 'tutorial', difficulty: 'beginner', duration: '1hr', tags: JSON.stringify(['design', 'ui', 'ux', 'figma']), goalTags: JSON.stringify(['learn-programming', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Design System from Scratch', description: 'Build a complete design system: tokens, components, patterns, and documentation. Using Figma and Storybook.', category: 'design', type: 'project', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['design-system', 'figma', 'storybook', 'components']), goalTags: JSON.stringify(['learn-programming', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=400&q=80', author: 'AdaptiveAI' },

  // Marketing & Growth
  { title: 'Growth Hacking for Tech Products', description: 'Viral loops, referral systems, product-led growth, and community building. Grow without a big marketing budget.', category: 'marketing', type: 'article', difficulty: 'intermediate', duration: '30min', tags: JSON.stringify(['growth', 'marketing', 'saas', 'viral']), goalTags: JSON.stringify(['build-startup', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1533750516457-a7f992034fec?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Content Marketing for Developers', description: 'Technical blogging, SEO for developers, developer advocacy, and documentation as marketing.', category: 'marketing', type: 'tutorial', difficulty: 'beginner', duration: '30min', tags: JSON.stringify(['content', 'marketing', 'blogging', 'seo']), goalTags: JSON.stringify(['build-startup', 'improve-communication']), imageUrl: 'https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=400&q=80', author: 'AdaptiveAI' },

  // Cybersecurity
  { title: 'Web Security Fundamentals', description: 'OWASP Top 10, XSS, CSRF, SQL injection, authentication vulnerabilities. Secure your applications from day one.', category: 'cybersecurity', type: 'tutorial', difficulty: 'intermediate', duration: '1hr', tags: JSON.stringify(['security', 'web', 'owasp', 'hacking']), goalTags: JSON.stringify(['learn-programming', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Ethical Hacking: CTF Challenge Set', description: '10 progressive capture-the-flag challenges. Network scanning, web exploitation, crypto, and binary exploitation.', category: 'cybersecurity', type: 'challenge', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['hacking', 'ctf', 'security', 'challenge']), goalTags: JSON.stringify(['learn-programming']), imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&q=80', author: 'AdaptiveAI' },

  // Finance
  { title: 'Personal Finance for Tech Workers', description: 'Salary negotiation, equity, tax optimization, investing, and financial independence. Built for high-earners in tech.', category: 'finance', type: 'article', difficulty: 'beginner', duration: '30min', tags: JSON.stringify(['finance', 'investing', 'career', 'money']), goalTags: JSON.stringify(['improve-career', 'improve-productivity']), imageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Startup Fundraising 101', description: 'Angel, seed, Series A: how venture capital works, term sheets, dilution, and finding the right investors for your stage.', category: 'finance', type: 'article', difficulty: 'intermediate', duration: '30min', tags: JSON.stringify(['fundraising', 'startup', 'vc', 'investment']), goalTags: JSON.stringify(['build-startup']), imageUrl: 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=400&q=80', author: 'AdaptiveAI' },

  // Communication
  { title: 'Technical Communication for Engineers', description: 'Write clear docs, present to stakeholders, give effective code reviews, and run meetings that matter.', category: 'communication', type: 'tutorial', difficulty: 'beginner', duration: '30min', tags: JSON.stringify(['communication', 'writing', 'presentation', 'career']), goalTags: JSON.stringify(['improve-communication', 'improve-career']), imageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=400&q=80', author: 'AdaptiveAI' },

  // Beginner-friendly
  { title: 'Git & GitHub: The Complete Workflow', description: 'Branching, pull requests, code review, rebasing, and team workflows. The Git knowledge every developer needs.', category: 'webdev', type: 'tutorial', difficulty: 'beginner', duration: '30min', tags: JSON.stringify(['git', 'github', 'version-control', 'basics']), goalTags: JSON.stringify(['learn-programming']), imageUrl: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Command Line Mastery', description: 'Bash, terminal navigation, scripting, pipes, and automation. 2x your developer productivity.', category: 'webdev', type: 'challenge', difficulty: 'beginner', duration: '1hr', tags: JSON.stringify(['bash', 'terminal', 'linux', 'productivity']), goalTags: JSON.stringify(['learn-programming', 'improve-productivity']), imageUrl: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=400&q=80', author: 'AdaptiveAI' },

  // Advanced/Startup Projects
  { title: 'Build a SaaS from Scratch', description: 'End-to-end SaaS project: auth, subscriptions (Stripe), multi-tenancy, email, analytics, and deployment. Production quality.', category: 'business', type: 'project', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['saas', 'stripe', 'fullstack', 'project']), goalTags: JSON.stringify(['build-startup', 'learn-programming']), imageUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'AI Agent Architecture', description: 'Design and implement autonomous AI agents with tool use, memory, planning, and multi-agent coordination.', category: 'ai', type: 'project', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['ai', 'agents', 'llm', 'architecture']), goalTags: JSON.stringify(['learn-ai', 'build-startup']), imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&q=80', author: 'AdaptiveAI' },
  { title: 'Kubernetes for Developers', description: 'Containers, pods, deployments, services, ingress, and Helm charts. Deploy your apps with confidence.', category: 'webdev', type: 'tutorial', difficulty: 'advanced', duration: '2hr+', tags: JSON.stringify(['kubernetes', 'docker', 'devops', 'deployment']), goalTags: JSON.stringify(['learn-programming', 'build-startup']), imageUrl: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=400&q=80', author: 'AdaptiveAI' },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Clean content table first
  await prisma.content.deleteMany();

  // Seed content
  for (const item of contentData) {
    await prisma.content.create({ data: item });
  }

  console.log(`✅ Seeded ${contentData.length} content items`);
  console.log('🎉 Database seeding complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
